apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-nas-config
  namespace: monitoring
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    positions:
      filename: /var/log/positions/positions.yaml

    scrape_configs:
      - job_name: nas-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: nas-logs
              __path__: /mnt/nas/WebLogs/*/web*/*/*

        pipeline_stages:
          - regex:
              expression: "/WebLogs/(?P<domain>[^/]+)/(?P<site>web[0-9]+)/(?P<log_type>[^/]+)/[^/]+$"
          - labels:
              domain: ""
              site: ""
              log_type: ""

